---
# vars file for hadoop-base

#hadoop_pkg:
#  version: 3.2.0
#  filename: hadoop-3.2.0.tar.gz
#  uri: https://www-eu.apache.org/dist/hadoop/common/hadoop-3.2.0/hadoop-3.2.0.tar.gz
#  checksum: md5:5AC41982DC50C96C897C70758FC54CA3
hadoop_pkg:
  version: 3.1.2
  filename: hadoop-3.1.2.tar.gz
  uri: https://www-eu.apache.org/dist/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz
  checksum: md5:4394AF12A81424DC225FE4F2DD02F274

java_home: /usr/lib/jvm/java/
yarn_rm_host: localhost
yarn_rm_port: 8032
yarn_rm_scheduler_port: 8030
yarn_rm_webapp_port: 8088
yarn_rm_webapp_https_port: 8090
yarn_rm_resource_tracker_port: 8031
yarn_rm_admin_port: 8033
yarn_rm_timeline_port: 8188
yarn_rm_timeline_https_port: 8190
yarn_rm_mrjobhistory_port: 19888
yarn_resource_vcores_multiplier: 1
yarn_resource_memory_multiplier: 1
yarn_available_vcores: '{{ ansible_processor_vcpus * yarn_resource_vcores_multiplier }}'
yarn_available_memory_mb: '{{ ansible_memtotal_mb * yarn_resource_memory_multiplier }}'
