---
# vars file for hive-master
hive_pkg:
  version: 3.1.2
  filename: apache-hive-3.1.2-bin.tar.gz
  uri: https://www-eu.apache.org/dist/hive/hive-3.1.2/apache-hive-3.1.2-bin.tar.gz
  checksum: md5:84a722c0f4c82d8c62914b321ea17661
  derby_version: 10.14.1.0

tez_pkg:
  version: 0.9.2
  filename: apache-tez-0.9.2-bin.tar.gz
  uri: https://www-eu.apache.org/dist/tez/0.9.2/apache-tez-0.9.2-bin.tar.gz
  checksum: md5:124b0dd83ba34e1a60cea50c8fb04f79

s3a_bucket: hive
s3a_endpoint: http://localhost:9000

hive_metastore_db: hive_metastore
hive_metastore_host: localhost
hive_metastore_port: 3306
hive_metastore_driver: mysql
hive_metastore_driver_class: 'com.mysql.jdbc.Driver'
hive_metastore_user: 'hive'
hive_metastore_password: 'hivemetastore'
hive_llap_instances: 2
hive_llap_memory_size: 2g
hive_llap_instance_name: llap0

zookeeper_quorum: localhost:2181
zookeeper_datadir: /var/lib/hive/zk
zookeeper_port: 2181
zookeeper_admin_port: 2180

yarn_rm_host: localhost
yarn_rm_port: 8032
yarn_rm_scheduler_port: 8030
yarn_rm_webapp_port: 8088
yarn_rm_webapp_https_port: 8090
yarn_rm_resource_tracker_port: 8031
yarn_rm_admin_port: 8033
yarn_rm_timeline_port: 8188
yarn_rm_timeline_https_port: 8190
yarn_rm_mrjobhistory_port: 19888
