---
# tasks file for hadoop-base
- name: Create Download Cache Directory
  local_action:
    module: file
    path: '{{ download_cache }}'
    state: directory

- name: Download Archives
  local_action:
    module: get_url
    url: '{{ item.uri }}'
    dest: '{{ download_cache }}/{{ item.filename }}'
    checksum: '{{ item.checksum }}'
  with_items:
    - '{{ hadoop_pkg }}'

- name: Setup dependencies
  dnf:
    name:
      - python3
      - python-unversioned-command
      - java-1.8.0-openjdk-devel
      - mysql-connector-java
      - postgresql-jdbc
      - grep
      - polkit

- name: Create KDP Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kdp/
    - /etc/kdp/env/
    - /etc/kdp/conf/

- name: Create Hadoop Groups
  group:
    name: '{{ item }}'
    state: present
  with_items:
    - hadoop
    - yarn

- name: Create Hadoop User
  user:
    name: '{{ item }}'
    group: 'hadoop'
    home: '/var/lib/{{ item }}/'
    create_home: no
    system: yes
    state: present
  with_items:
    - yarn


- name: Create Hadoop Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: hadoop
    mode: 775
  with_items:
    - /var/lib/hadoop/
    - /var/log/hadoop/

- name: Create YARN Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: yarn
    group: yarn
    mode: 0775
  with_items:
    - /var/lib/yarn/
    - /var/log/yarn/

- name: Extract Archives
  unarchive: 
    src: "{{ item.src }}"
    dest: "/opt/kdp"
    creates: "{{ item.creates }}"
  with_items:
    - { src: '{{ download_cache }}/{{ hadoop_pkg.filename }}',
        creates: '/opt/kdp/hadoop-{{ hadoop_pkg.version }}' }

- name: Create Symlinks
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '/opt/kdp/hadoop-{{ hadoop_pkg.version }}', dest: /opt/hadoop }

- name: Copy AWS Jars
  copy:
    src: '/opt/kdp/hadoop-{{ hadoop_pkg.version }}/share/hadoop/tools/lib/{{ item }}'
    dest: '/opt/kdp/hadoop-{{ hadoop_pkg.version }}/share/hadoop/common/lib/'
    remote_src: yes
  with_items:
    - 'hadoop-aws-{{ hadoop_pkg.version }}.jar'
    - aws-java-sdk-bundle-1.11.271.jar

- name: Copy Database Drivers
  copy:
    src: '{{ item }}'
    dest: '/opt/kdp/hadoop-{{ hadoop_pkg.version }}/share/hadoop/common/lib/'
    remote_src: yes
  with_items:
    - /usr/share/java/mysql-connector-java.jar
    - /usr/share/java/postgresql-jdbc.jar 


- name: Install Hadoop Configurations
  template:
    src: 'conf/{{ item }}.j2'
    dest: '/etc/kdp/conf/{{ item }}'
  with_items:
    - yarn-env.sh
    - hadoop-env.sh
    - hdfs-site.xml
    - yarn-site.xml
    - capacity-scheduler.xml
    - core-site.xml
    - mapred-site.xml
    - log4j.properties


- name: Install Environment Profile
  template:
    src: etc/profile.d/kdp.sh.j2
    dest: /etc/profile.d/kdp.sh

- name: Install Environment Files
  template:
    src: 'env/{{ item }}.j2'
    dest: '/etc/kdp/env/{{ item }}'
  with_items:
    - '0-hadoop.sh'

- name: Install KDP enable script
  template:
    src: bin/kdp-enable
    dest: /usr/bin/kdp-enable
    mode: 0755
