---
# tasks file for hadoop-jupyter
#
- fail: 
    msg: 'CentOS/RHEL != 7 is not supported'
  when: (ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat") and ansible_facts['distribution_major_version']|int == 7

- fail: 
    msg: 'Fedora < 30 is not supported'
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version']|int < 30

- name: Set Distro Facts (Fedora)
  set_fact:
    distro_family: fedora
  when: ansible_facts['distribution'] == "Fedora"

- name: Set Distro Facts (CentOS/RHEL)
  set_fact:
    distro_family: el
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"


# ======== SCL =========
- name: Setup SCL (CentOS)
  yum:
    name:
      - centos-release-scl
  when: ansible_facts['distribution'] == "CentOS"

- name: Setup SCL (RHEL)
  rhsm_repository:
    name: 
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-optional-rpms
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == 7

# ====== System Deps =========
- name: Setup system dependencies (CentOS/RHEL)
  yum:
    name:
      - rh-nodejs8-npm
      - python36
      - python36-devel
      - python36-pip
      - python36-virtualenv
  when: distro_family == 'el'

- name: Setup system dependencies (Fedora)
  yum:
    name:
      - python3
      - python3-devel
      - python3-pip
      - python3-virtualenv
      - npm
  when: distro_family == 'fedora'

- name: Setup system dependencies (Common)
  yum:
    name:
      - gcc
      - gcc-c++
      - mod_ssl
      - pandoc

- name: Setup LaTeX dependencies
  yum:
    name:
      - texlive-xetex
      - texlive-tcolorbox
      - texlive-adjustbox
      - texlive-upquote
      - texlive-titling 
      - texlive-ulem

# ========== Jupyter Init ========
- name: Setup Jupyter directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /etc/jupyterhub
    - /var/lib/jupyterhub
    - /var/log/jupyterhub

- name: Install NPM Configurable HTTP Proxy (CentOS/RHEL)
  command: scl enable rh-nodejs8 -- npm install -g configurable-http-proxy
  args:
    creates: /opt/rh/rh-nodejs8/root/usr/lib/node_modules/configurable-http-proxy
  when: distro_family == 'el'

- name: Install NPM Configurable HTTP Proxy (Fedora)
  command: npm install -g configurable-http-proxy
  args:
    creates: /usr/lib/node_modules/configurable-http-proxy 
  when: distro_family == 'fedora'

- name: Check existing virtualenv
  stat:
    path: /opt/jupyterhub/
  register: has_jupyterhub
  when: reinitialize == True

- name: Stop JupyterHub
  systemd:
    name: jupyterhub
    state: stopped
  when: reinitialize == True and has_jupyterhub.stat.exists == True

- name: Remove existing virtualenv
  file:
    path: /opt/jupyterhub/
    state: absent
  when: reinitialize == True

- name: Setup Jupyter virtualenv (CentOS/RHEL)
  command: virtualenv-3 /opt/jupyterhub/
  args:
    creates: /opt/jupyterhub/
  when: distro_family == 'el'


- name: Setup Jupyter virtualenv (Fedora)
  command: virtualenv --python /usr/bin/python3.7 /opt/jupyterhub/
  args:
    creates: /opt/jupyterhub/
  when: distro_family == 'fedora'


- name: Setup Jupyter Python Packages
  command: "/opt/jupyterhub/bin/pip install {{ item.package }}=={{ item.version }}"
  args:
    creates: "/opt/jupyterhub/lib64/python*/site-packages/{{ item.pymodule }}"
  with_items:
    - { package: jupyterlab,
        version: '1.1.0',
        pymodule: jupyterlab }
    - { package: jupyterhub,
        version: '1.0.0',
        pymodule: jupyterhub }
    - { package: bokeh,
        version: '1.3.4',
        pymodule: bokeh }

- name: Setup Jupyterlab Extensions (Fedora)
  command: "/opt/jupyterhub/bin/jupyter labextension install {{ item.extension }}"
  args:
    creates: "/opt/jupyterhub/share/jupyter/lab/extensions/{{ item.creates }}"
  with_items:
    - { extension: '@jupyter-widgets/jupyterlab-manager',
        creates: jupyter-widgets-jupyterlab-manager*  }
    - { extension: jupyterlab_bokeh,
        creates: jupyterlab_bokeh* }
  when: distro_family == 'fedora'


- name: Setup Jupyterlab Extensions (CentOS/RHEL)
  command: "scl enable rh-nodejs8 -- /opt/jupyterhub/bin/jupyter labextension install {{ item.extension }}"
  args:
    creates: "/opt/jupyterhub/share/jupyter/lab/extensions/{{ item.creates }}"
  with_items:
    - { extension: '@jupyter-widgets/jupyterlab-manager',
        creates: jupyter-widgets-jupyterlab-manager*  }
    - { extension: jupyterlab_bokeh,
        creates: jupyterlab_bokeh* }
  when: distro_family == 'el'

- name: Rebuild Jupyterlab Asset Files (Fedora)
  command: /opt/jupyterhub/bin/jupyter lab build
  when: rebuild_assets == True and distro_family == 'fedora'

- name: Rebuild Jupyterlab Asset Files (CentOS/RHEL)
  command: 'scl enable rh-nodejs8 -- /opt/jupyterhub/bin/jupyter lab build'
  when: rebuild_assets == True and distro_family == "el"

# ========= SystemD Settings =========

- name: Install JupyterHub Configuration
  copy:
    src: 'common/etc/jupyterhub/jupyterhub_config.py'
    dest: /etc/jupyterhub/jupyterhub_config.py

- name: Install JupyterHub EnvironmentFile
  copy:
    src: 'common/etc/sysconfig/jupyterhub'
    dest: /etc/sysconfig/jupyterhub

- name: Generate SSL Certificate
  command: /usr/libexec/httpd-ssl-gencerts
  args:
    creates: /etc/pki/tls/private/localhost.key

- name: Install SystemD Service
  copy:
    src: '{{ distro_family }}/systemd/jupyterhub.service'
    dest: /usr/lib/systemd/system/jupyterhub.service

- name: Reload JupyterHub SystemD
  systemd:
    name: jupyterhub
    enabled: yes
    daemon_reload: yes
    state: restarted
